# Generated by Django 4.0.4 on 2022-04-17 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://d2dgtayfmpkokn.cloudfront.net/wp-content/uploads/sites/602/2021/03/11182342/2020_10_27_JLRNA_LandRover_Inventory_Placeholder_Image-1.jpg', max_length=700),
        ),
    ]
